"""Generate the note's derived TeX inputs from committed StaleLine files (never typed numbers).

Writes, next to this script:
  phantom.tex       phantom_* keys from origin/check-phantom:results/robustness_phantom/ (commit recorded)
  extra.tex         spec_*, run_*, laggard_*, count_* keys read from committed code and result files on main
  prereg_table.tex  Appendix A pre-registration timeline, parsed from docs/holdout_run_disclosure.md
  posthoc_table.tex Appendix B table, parsed from results/posthoc/SUMMARY.md

Every key is written with a "% source" comment. Usage: python3 make_tables.py
"""
from __future__ import annotations

import csv
import io
import json
import os
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = Path(os.environ["STALELINE_REPO"]).resolve() if os.environ.get("STALELINE_REPO") else (
    HERE.parent / "staleline" if (HERE.parent / "staleline" / ".git").exists() else HERE.parents[1])
PHANTOM_REF = "origin/check-phantom"


def git(*args: str) -> str:
    return subprocess.run(["git", "-C", str(REPO), *args], check=True, capture_output=True, text=True).stdout


def show(ref: str, path: str) -> str:
    return git("show", f"{ref}:{path}")


def tex_escape(s: str) -> str:
    s = str(s)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\^{}")):
        s = s.replace(a, b)
    s = s.replace(">=", r"$\geq$").replace("<=", r"$\leq$").replace(" > ", r" $>$ ").replace(" < ", r" $<$ ")
    s = s.replace("--", "-{}-")
    return s


def neg(x: str) -> str:
    """Typeset a leading minus as a real minus sign, inside math."""
    return x


class Keys:
    def __init__(self) -> None:
        self.rows: list[tuple[str, str, str]] = []

    def add(self, key: str, value, source: str) -> None:
        self.rows.append((key, str(value), source))

    def write(self, path: Path, header: str) -> None:
        lines = [f"% GENERATED by make_tables.py; do not edit. {header}",
                 r"\providecommand{\defval}[2]{\expandafter\def\csname val@#1\endcsname{#2}}"]
        for k, v, src in self.rows:
            lines.append(f"\\defval{{{k}}}{{{v}}}  % {src}")
        path.write_text("\n".join(lines) + "\n")


def f(x: float, d: int) -> str:
    return f"{x:.{d}f}"


def pct(x: float, d: int = 1) -> str:
    return f"{100 * x:.{d}f}\\%"


def thousands(n) -> str:
    return f"{int(n):,}".replace(",", "{,}")


def sci(x: float) -> str:
    m, e = f"{x:.2e}".split("e")
    return f"${m}\\times 10^{{{int(e)}}}$"


# ---------- phantom ----------

def phantom(k: Keys) -> None:
    sha = git("rev-parse", "--short", PHANTOM_REF).strip()
    src = f"git show {sha}:results/robustness_phantom/"
    s = {r["venue"]: r for r in csv.DictReader(io.StringIO(show(PHANTOM_REF, "results/robustness_phantom/item2_summary.csv")))}
    ka, pm = s["kalshi"], s["polymarket"]
    k.add("phantom_commit", sha, "git rev-parse " + PHANTOM_REF)
    k.add("phantom_games", ka["games"], src + "item2_summary.csv: games")
    k.add("phantom_kalshi_rows", thousands(ka["rows"]), src + "item2_summary.csv: kalshi rows")
    k.add("phantom_kalshi_residue_rows", thousands(ka["residue_rows"]), src + "item2_summary.csv: kalshi residue_rows")
    k.add("phantom_kalshi_residue_share", pct(float(ka["share_residue_rows"]), 2), src + "item2_summary.csv: kalshi share_residue_rows")
    k.add("phantom_kalshi_grid_share", pct(float(ka["share_grid_mid_differ"]), 2), src + "item2_summary.csv: kalshi share_grid_mid_differ")
    k.add("phantom_kalshi_mid_value_changed", ka["mid_differ_both_defined"], src + "item2_summary.csv: kalshi mid_differ_both_defined")
    k.add("phantom_kalshi_games_over_threshold", ka["games_share_mid_differ_gt_0.1pct"], src + "item2_summary.csv: kalshi games_share_mid_differ_gt_0.1pct")
    k.add("phantom_kalshi_max_game_share", pct(float(ka["max_game_share_mid_differ"]), 1), src + "item2_summary.csv: kalshi max_game_share_mid_differ")
    k.add("phantom_pm_residue_rows", thousands(pm["residue_rows"]), src + "item2_summary.csv: polymarket residue_rows")
    c = {r["test"]: r for r in csv.DictReader(io.StringIO(show(PHANTOM_REF, "results/robustness_phantom/lead_comparison.csv")))}
    for name, tag in (("polymarket.com", "pmcom"), ("Polymarket US", "pmus")):
        r = c[name]
        k.add(f"phantom_{tag}_pre_result", r["pre_result"], src + f"lead_comparison.csv: {name} pre_result")
        k.add(f"phantom_{tag}_robust_result", r["robust_result"], src + f"lead_comparison.csv: {name} robust_result")
        k.add(f"phantom_{tag}_robust_n", r["robust_n_qualifying"], src + f"lead_comparison.csv: {name} robust_n_qualifying")
        k.add(f"phantom_{tag}_robust_median_lag_s", f(float(r["robust_median_corrected_lag_s"]), 1), src + f"lead_comparison.csv: {name} robust_median_corrected_lag_s")
        k.add(f"phantom_{tag}_robust_mw_p", sci(float(r["robust_mann_whitney_p"])) if float(r["robust_mann_whitney_p"]) < 0.001 else f(float(r["robust_mann_whitney_p"]), 3),
              src + f"lead_comparison.csv: {name} robust_mann_whitney_p")


# ---------- extra (main branch, committed files) ----------

def const(text: str, name: str) -> str:
    m = re.search(rf"^{name}\s*=\s*(.+?)(\s*#.*)?$", text, re.M)
    if not m:
        raise KeyError(name)
    return m.group(1).strip()


def extra(k: Keys) -> None:
    head = git("rev-parse", "--short", "HEAD").strip()
    a = show("HEAD", "strategy_a.py")
    b = show("HEAD", "strategy_b.py")
    k.add("spec_main_commit", head, "git rev-parse HEAD (staleline main)")
    seal = re.search(r'SEAL = pd.Timestamp\("([0-9-]+)"', a).group(1)
    k.add("spec_seal_date", seal, "strategy_a.py: SEAL")
    k.add("spec_qty", const(a, "QTY"), "strategy_a.py: QTY")
    k.add("spec_webull_fee", f(float(const(a, "WEBULL_PER_CONTRACT")), 2), "strategy_a.py: WEBULL_PER_CONTRACT")
    k.add("spec_kalshi_rate", f(float(const(a, "KALSHI_DIRECT_RATE")), 2), "strategy_a.py: KALSHI_DIRECT_RATE")
    k.add("spec_latency_s", f(float(const(a, "LATENCY_S")), 0), "strategy_a.py: LATENCY_S")
    k.add("spec_A_entry_min", str(eval(const(a, "ENTRY_BEFORE_KICKOFF_S")) // 60), "strategy_a.py: ENTRY_BEFORE_KICKOFF_S / 60")
    k.add("spec_A_half_spread_c", f(100 * float(const(a, "HALF_SPREAD")), 0), "strategy_a.py: HALF_SPREAD x 100")
    th = eval(const(a, "THETAS"))
    k.add("spec_A_thetas", ", ".join(f(t, 2) for t in th), "strategy_a.py: THETAS")
    kg, mg, tg = eval(re.search(r"K_GRID, M_GRID, T_GRID = (.+)", b).group(1))
    k.add("spec_B_k_grid_c", ", ".join(f(100 * x, 0) for x in kg), "strategy_b.py: K_GRID x 100")
    k.add("spec_B_m_grid_s", ", ".join(str(x) for x in mg), "strategy_b.py: M_GRID")
    k.add("spec_B_T_grid_s", ", ".join(str(x) for x in tg), "strategy_b.py: T_GRID")
    k.add("spec_B_n_settings", str(len(kg) * len(mg) * len(tg)), "strategy_b.py: len(K_GRID) x len(M_GRID) x len(T_GRID)")
    k.add("spec_B_half_spread_c", f(100 * float(const(b, "HALF_SPREAD")), 1), "strategy_b.py: HALF_SPREAD x 100")
    k.add("spec_B_stale_s", const(b, "STALE_S"), "strategy_b.py: STALE_S")
    # run metadata
    log = show("HEAD", "results/holdout/RUN_LOG.md")
    k.add("run_sha", re.search(r"git sha: ([0-9a-f]{7})", log).group(1), "results/holdout/RUN_LOG.md: git sha")
    k.add("run_start", re.search(r"start: (.+ ET)", log).group(1), "results/holdout/RUN_LOG.md: start")
    k.add("run_end", re.search(r"end: (.+ ET)", log).group(1).split(" ", 1)[1], "results/holdout/RUN_LOG.md: end")
    # laggard latency curve (pre-registered exploratory laggard)
    rows = list(csv.DictReader(io.StringIO(show("HEAD", "results/holdout/laggard_latency_curve.csv"))))
    src = "results/holdout/laggard_latency_curve.csv"
    for venue, lat, tag in (("polymarket", "1.0", "pmcom_1s"), ("polymarket_us", "0.0", "pmus_0s"),
                            ("polymarket_us", "1.0", "pmus_1s"), ("polymarket_us", "5.0", "pmus_5s"),
                            ("polymarket_us", "10.0", "pmus_10s")):
        r = next(x for x in rows if x["venue"] == venue and x["latency_s"] == lat)
        k.add(f"laggard_{tag}_n", thousands(r["n_trades"]), f"{src}: n_trades ({venue}, {lat} s)")
        k.add(f"laggard_{tag}_edge_c", f(float(r["edge_cents_mean"]), 2), f"{src}: edge_cents_mean ({venue}, {lat} s)")
        k.add(f"laggard_{tag}_ci", f"[{f(float(r['edge_ci_low']), 2)}, {f(float(r['edge_ci_high']), 2)}]",
              f"{src}: edge_ci_low, edge_ci_high ({venue}, {lat} s)")
    # lead-test p-values, formatted
    srcL = "results/holdout/lead_decisions.json"
    L = json.loads(show("HEAD", srcL))
    for name, tag in (("polymarket.com", "pmcom"), ("Polymarket US", "pmus")):
        p = L[name]["mann_whitney_p"]
        k.add(f"lead_{tag}_mw_p", sci(p) if p < 0.001 else f(p, 3), f"{srcL}: {name}.mann_whitney_p")
    # Strategy A underdog placebo, holdout (primary sample)
    srcA = "results/holdout/strategy_a_summary.csv"
    pr = next(r for r in csv.DictReader(io.StringIO(show("HEAD", srcA)))
              if r["leg"] == "placebo (underdog)" and r["sample"] == "primary")
    k.add("A_placebo_roc_webull", f(float(pr["roc_webull"]), 3), f"{srcA}: roc_webull (placebo (underdog), primary)")
    k.add("A_placebo_trades", pr["entered"], f"{srcA}: entered (placebo (underdog), primary)")
    # deflated Sharpe, formatted, from the post-hoc DSR file (stored 22-trial values and the current line)
    srcD = "results/posthoc/dsr_posthoc.json"
    d = json.loads(show("HEAD", srcD))
    n22 = re.search(r"total_(\d+)", next(iter(d["stored_total_22"]))).group(1)
    k.add("count_trials_prereg", n22, f"{srcD}: stored_total_22 key suffix")
    k.add("count_trials_final", str(d["n_trials"]), f"{srcD}: n_trials")
    for book in ("A", "B", "combined"):
        k.add(f"dsr_{book}_prereg", sci(d["stored_total_22"][f"OOS.{book}.deflated_sharpe_total_{n22}"]),
              f"{srcD}: stored_total_22.OOS.{book}.deflated_sharpe_total_{n22}")
        k.add(f"dsr_{book}_final", sci(d["values"][f"OOS.{book}.deflated_sharpe_total_{d['n_trials']}"]),
              f"{srcD}: values.OOS.{book}.deflated_sharpe_total_{d['n_trials']}")
    # counts from the post-hoc summary
    summ = show("HEAD", "results/posthoc/SUMMARY.md")
    ideas = [l for l in summ.splitlines() if l.startswith("| ") and not l.startswith("| idea") and "|---" not in l
             and re.match(r"\| (\d+|T&S laggard) \|", l)]
    k.add("count_posthoc_ideas", str(sum(1 for l in ideas if re.match(r"\| \d+ \|", l))), "results/posthoc/SUMMARY.md: numbered idea rows")
    k.add("count_posthoc_rows", str(len(ideas)), "results/posthoc/SUMMARY.md: idea rows incl. T&S laggard")
    nvar = len(list(csv.DictReader(io.StringIO(show("HEAD", "experiments/variants.csv")))))
    k.add("count_variants_rows", str(nvar), "experiments/variants.csv: data rows")
    # Strategy A training plateau: roc_webull for the favorite leg at each theta, from the variants.csv notes
    srcV = "experiments/variants.csv"
    for row in csv.DictReader(io.StringIO(show("HEAD", srcV))):
        note = row.get("notes", "")
        m = re.search(r"Strategy A v3\+A1-A3; theta ([0-9.]+); favorite;.*roc_webull (-?[0-9.]+)", note)
        if m and m.group(1) in ("0.7", "0.9"):
            tag = {"0.7": "070", "0.9": "090"}[m.group(1)]
            k.add(f"plateau_A_roc_webull_{tag}", m.group(2), f"{srcV}: notes roc_webull (strategy_a training, theta {m.group(1)}, favorite)")
    # Strategy A capacity: contracts traded at or better than A's fill in its fill window (training, theta 0.80)
    srcC = "docs/results/a_capacity.csv"
    cap = list(csv.DictReader(io.StringIO(show("HEAD", srcC))))

    def q(xs: list[float], p: float) -> float:  # linear interpolation, same as pandas default
        xs = sorted(xs); h = (len(xs) - 1) * p; lo = int(h); hi = min(lo + 1, len(xs) - 1)
        return xs[lo] + (h - lo) * (xs[hi] - xs[lo])
    for grp, rows_ in (("all", cap), ("cfb", [r for r in cap if r["league"] == "CFB"]),
                       ("nfl", [r for r in cap if r["league"] == "NFL"])):
        v = [float(r["contracts_at_or_better"]) for r in rows_]
        k.add(f"cap_A_{grp}_n", str(len(v)), f"{srcC}: rows ({grp})")
        k.add(f"cap_A_{grp}_median", thousands(round(q(v, 0.5))), f"{srcC}: median contracts_at_or_better ({grp})")
        k.add(f"cap_A_{grp}_p25", thousands(round(q(v, 0.25))), f"{srcC}: 25th pct contracts_at_or_better ({grp})")
        k.add(f"cap_A_{grp}_p75", thousands(round(q(v, 0.75))), f"{srcC}: 75th pct contracts_at_or_better ({grp})")
        k.add(f"cap_A_{grp}_share_below10", pct(sum(x < 10 for x in v) / len(v), 1), f"{srcC}: share contracts_at_or_better < 10 ({grp})")
    # Post-hoc meta-model and context map (branches not merged; training walk-forward only)
    for ref, path, keymap in (
        ("origin/posthoc-meta", "results/posthoc_meta/results.csv",
         {"M1 logistic": "meta_m1", "M2 tree depth 3": "meta_m2"}),
        ("origin/posthoc-ctxmap", "results/posthoc_ctxmap/walkforward_results.csv",
         {"context map N=20": "ctx_n20", "context map N=50": "ctx_n50"})):
        sha = git("rev-parse", "--short", ref).strip()
        for r in csv.DictReader(io.StringIO(show(ref, path))):
            if r["book"] in keymap:
                t = keymap[r["book"]]
                src = f"git show {sha}:{path}: {r['book']}"
                k.add(f"posthoc_{t}_trades", thousands(r["trades"]), src + " trades")
                k.add(f"posthoc_{t}_roc", f(float(r["roc_mean"]), 3), src + " roc_mean")
                k.add(f"posthoc_{t}_roc_ci", f"[{f(float(r['roc_ci_lo']), 3)}, {f(float(r['roc_ci_hi']), 3)}]", src + " roc_ci_lo, roc_ci_hi")
        k.add(f"posthoc_{'meta' if 'meta' in ref else 'ctx'}_commit", sha, "git rev-parse " + ref)
    res = show("origin/posthoc-meta", "results/posthoc_meta/RESULTS.md")
    m = re.search(r"Out-of-sample AUC for P\(net > 0\) is ([0-9.]+) \(M1\)", res)
    k.add("posthoc_meta_auc_m1", m.group(1), "results/posthoc_meta/RESULTS.md (origin/posthoc-meta): out-of-sample AUC, M1")
    m = re.search(r"out-of-sample\s+correlation of ([0-9]+\.[0-9]+)", res)
    k.add("posthoc_meta_ridge_corr", m.group(1), "results/posthoc_meta/RESULTS.md (origin/posthoc-meta): ridge out-of-sample correlation")
    for ref, tag in (("origin/posthoc-search", "search"), ("origin/posthoc-costside", "costside")):
        sha = git("rev-parse", "--short", ref).strip()
        files = git("diff", "--name-only", "origin/main..." + ref).split()
        k.add(f"posthoc_{tag}_commit", sha, "git rev-parse " + ref)
    # After-submission post-hoc work: counts from the ledger on main, corrections from each branch's correction.json
    srcL2 = "results/posthoc/LEDGER.md"
    led = show("HEAD", srcL2)
    rows_l = [[c.strip() for c in l.strip().strip("|").split("|")] for l in led.splitlines() if l.startswith("| 2026")]
    new_branches = ("posthoc-search", "posthoc-costside", "posthoc-costside-maker", "posthoc-costside-patterns",
                    "posthoc-unsup", "posthoc-regress", "posthoc-leadlag2", "posthoc-laya")
    tot = 0
    for b in new_branches:
        r = next(x for x in rows_l if x[1] == b)
        n = int(re.match(r"(\d+)", r[3]).group(1))
        tot += n
        k.add(f"led_{b.replace('posthoc-', '').replace('-', '_')}_trials", str(n), f"{srcL2}: {b} trials evaluated")
    mmref = "origin/posthoc-mm-signal"
    shaM = git("rev-parse", "--short", mmref).strip()
    mmled = show(mmref, "results/posthoc_mm_signal/LEDGER.md")
    mmn = int(re.search(r"Variants: (\d+)", mmled).group(1))
    k.add("led_mm_trials", str(mmn), f"git show {shaM}:results/posthoc_mm_signal/LEDGER.md: Variants")
    tot += mmn
    for r in csv.DictReader(io.StringIO(show(mmref, "results/posthoc_mm_signal/results.csv"))):
        if r["venue"] == "polymarket.com" and r["rule"] == "F1" and float(r["L"]) == 1.0:
            src = f"git show {shaM}:results/posthoc_mm_signal/results.csv: polymarket.com F1 L 1.0"
            k.add("mm_pm_sminusn", f(float(r["SminusN_pnl60"]), 0), src + " SminusN_pnl60")
            k.add("mm_pm_sminusn_ci", f"[{f(float(r['SminusN_pnl60_lo']), 0)}, {f(float(r['SminusN_pnl60_hi']), 0)}]", src + " SminusN_pnl60_lo, _hi")
    k.add("mm_commit", shaM, "git rev-parse " + mmref)
    nc = json.loads(show(mmref, "results/posthoc_mm_signal/n_check.json"))
    srcN = f"git show {shaM}:results/posthoc_mm_signal/n_check.json"
    k.add("mmN_pnl60_c", f(nc["pnl60_c_per_contract"][0], 2), srcN + ": pnl60_c_per_contract[0]")
    k.add("mmN_pnl60_ci", f"[{f(nc['pnl60_c_per_contract'][1], 2)}, {f(nc['pnl60_c_per_contract'][2], 2)}]", srcN + ": pnl60_c_per_contract[1:]")
    k.add("mmN_pnl60_excl5_c", f(nc["pnl60_excl_top5_c_per_contract"][0], 2), srcN + ": pnl60_excl_top5_c_per_contract[0]")
    k.add("mmN_set_ci", f"[{f(nc['pnlset_c_per_contract'][1], 2)}, {f(nc['pnlset_c_per_contract'][2], 2)}]", srcN + ": pnlset_c_per_contract[1:]")
    gm = list(csv.DictReader(io.StringIO(show(mmref, "results/posthoc_mm_signal/n_detail_games.csv"))))
    srcG = f"git show {shaM}:results/posthoc_mm_signal/n_detail_games.csv"
    pn = sorted((float(r["pnl60"]) for r in gm), reverse=True)
    k.add("mmN_top5_usd", f(sum(pn[:5]), 2), srcG + ": sum of the 5 largest pnl60")
    k.add("mmN_all_usd", f(sum(pn), 2), srcG + ": sum of pnl60")
    rtc = sum(float(r["rt_contracts"]) for r in gm); rtp = sum(float(r["rt_pnl"]) for r in gm)
    k.add("mmN_rt_c", f(100 * rtp / rtc, 2), srcG + ": 100 x sum rt_pnl / sum rt_contracts")
    k.add("mmN_spread_c", f(nc["spread_captured_c_per_contract"], 2), srcN + ": spread_captured_c_per_contract")
    k.add("mmN_adverse_c", f(-nc["mark_to_mid_60s_c_per_contract"], 2), srcN + ": minus mark_to_mid_60s_c_per_contract")
    v4 = git("log", "-1", "--format=%h", "HEAD", "--", "HYPOTHESIS_v4.md").strip()
    v4r = next(x for x in rows_l if x[1] == "posthoc-mm-v4")
    m = re.search(r"\((\d+) Oct 3 games after 20:00 ET, all recordings end ([0-9:]+) ET", v4r[4])
    k.add("v4_ts1_n", m.group(1), f"{srcL2}: posthoc-mm-v4 status")
    k.add("v4_ts1_end", m.group(2), f"{srcL2}: posthoc-mm-v4 status")
    vx = next(x for x in rows_l if x[1] == "posthoc-mm-v4-extra")
    m = re.search(r"A (\d+) fills \+\$([0-9.]+) at \+60 s, B (\d+) fills \+\$([0-9.]+)", vx[4])
    k.add("v4x_a_fills", m.group(1), f"{srcL2}: posthoc-mm-v4-extra"); k.add("v4x_a_usd", m.group(2), f"{srcL2}: posthoc-mm-v4-extra")
    k.add("v4x_b_fills", m.group(3), f"{srcL2}: posthoc-mm-v4-extra"); k.add("v4x_b_usd", m.group(4), f"{srcL2}: posthoc-mm-v4-extra")
    k.add("v4_commit", v4, "git log -1 -- HYPOTHESIS_v4.md")
    sp = {r["bucket"]: r for r in csv.DictReader(io.StringIO(show(mmref, "results/posthoc_mm_signal/n_detail_spread.csv")))}
    k.add("mmN_1c_c", f(float(sp["1c"]["pnl60_c_per_contract"]), 2), f"git show {shaM}:results/posthoc_mm_signal/n_detail_spread.csv: 1c pnl60_c_per_contract")
    k.add("led_new_trials", str(tot), f"{srcL2}: sum of trials evaluated over {', '.join(new_branches)}; plus posthoc-mm-signal")
    k.add("led_grand_total", str(nvar + 4 + tot), "variants.csv rows + 4 (meta, ctxmap) + led_new_trials")
    llm = next(x for x in rows_l if x[1] == "posthoc-llm")
    k.add("led_llm_planned", re.match(r"(\d+)", llm[2]).group(1), f"{srcL2}: posthoc-llm trials planned")
    k.add("led_llm_evaluated", re.match(r"(\d+)", llm[3]).group(1), f"{srcL2}: posthoc-llm trials evaluated")
    m = re.search(r"Databento spend \$([0-9.]+)", led)
    k.add("led_databento_usd", f(float(m.group(1)), 2), f"{srcL2}: data-cme-train Databento spend")
    srch = next(x for x in rows_l if x[1] == "posthoc-search")
    m = re.search(r"SPA p ([0-9.]+)", srch[4])
    k.add("rc_search_spa_p", m.group(1), f"{srcL2}: posthoc-search SPA p")
    cj = json.loads(show("origin/posthoc-leadlag2", "results/posthoc_leadlag2/correction.json"))
    shaL = git("rev-parse", "--short", "origin/posthoc-leadlag2").strip()
    k.add("rc_all_trials", str(cj["trials_in_correction"]), f"git show {shaL}:results/posthoc_leadlag2/correction.json: trials_in_correction")
    k.add("rc_all_p", f(cj["rc_p_best_by_t"], 2), f"git show {shaL}:results/posthoc_leadlag2/correction.json: rc_p_best_by_t")
    k.add("rc_all_best_t", f(cj["best_t"], 2), f"git show {shaL}:results/posthoc_leadlag2/correction.json: best_t")
    ps = []
    for ref, path in (("origin/posthoc-regress", "results/posthoc_regress/correction.json"),
                      ("origin/posthoc-unsup", "results/posthoc_unsup/correction.json"),
                      ("origin/posthoc-costside", "results/posthoc_costside/correction.json"),
                      ("origin/posthoc-leadlag2", "results/posthoc_leadlag2/correction.json")):
        d_ = json.loads(show(ref, path))
        ps.append(d_.get("rc_p", d_.get("rc_p_best_by_t")))
    k.add("rc_min_p", f(min(ps), 2), "min Reality Check p over posthoc-regress, -unsup, -costside, -leadlag2 correction.json")
    cme = next(x for x in rows_l if x[1] == "posthoc-kalshi-cme (Stage 1)")
    m = re.search(r"\((-[0-9.]+) to (-[0-9.]+) c per contract\)", cme[8])
    k.add("cme_cells_worst_c", m.group(2), f"{srcL2}: posthoc-kalshi-cme Stage 1 cell range (worst)")
    k.add("cme_cells_best_c", m.group(1), f"{srcL2}: posthoc-kalshi-cme Stage 1 cell range (best)")
    k.add("cme_n_cells", re.match(r"(\d+)", cme[2]).group(1), f"{srcL2}: posthoc-kalshi-cme Stage 1 cells")
    k.add("count_extra_trials_unlogged", "4", "posthoc-meta RESULTS.md (Variants: 2) + posthoc-ctxmap walkforward (N=20, N=50): rows not yet in variants.csv")


# ---------- tables ----------

def prereg_table() -> str:
    text = show("HEAD", "docs/holdout_run_disclosure.md")
    sec = text.split("## Pre-registration, in order")[1].split("\n## ")[0]
    rows = [l for l in sec.splitlines() if re.match(r"\| [0-9a-f]{7} \|", l)]
    out = [r"% GENERATED by make_tables.py from docs/holdout_run_disclosure.md (Pre-registration table); do not edit.",
           r"\begin{footnotesize}", r"\begin{tabularx}{\textwidth}{@{}l l X@{}}", r"\toprule",
           r"Commit & ET time & What \\", r"\midrule"]
    for l in rows:
        c, t, w = [x.strip() for x in l.strip("|").split("|")]
        out.append(f"\\texttt{{{c}}} & {tex_escape(t)} & {tex_escape(w)} \\\\")
    out += [r"\bottomrule", r"\end{tabularx}", r"\end{footnotesize}"]
    return "\n".join(out) + "\n"


SHORT = {  # hypothesis in a few words (wording only; no numbers)
    "T&S laggard": "PM US prints lead Kalshi",
    "1": "Kalshi complement mispricing",
    "2": "polymarket.com leads sub-second",
    "3": "fade large Kalshi prints",
    "4": "late-game favorite underpriced",
    "6": "buy winner after end marker",
    "7": "pregame cross-venue gap",
    "8": "fade pregame taker flow",
    "9": "ESPN win prob.\\ vs Kalshi",
    "10": "fade scoring-play moves",
    "11": "lag and cross-venue arbitrage",
    "12": "in-game cross-venue gap",
    "13": "NFL closing line as fair value",
}


def cut(s: str, n: int) -> str:
    s = s.strip()
    return s if len(s) <= n else s[: n - 1].rsplit(" ", 1)[0] + "…"


def posthoc_table() -> str:
    text = show("HEAD", "results/posthoc/SUMMARY.md")
    rows = [l for l in text.splitlines() if re.match(r"\| (\d+|T&S laggard) \|", l)]
    out = [r"% GENERATED by make_tables.py from results/posthoc/SUMMARY.md; do not edit.",
           r"\begin{footnotesize}", r"\setlength{\tabcolsep}{3pt}",
           r"\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{0.9cm} >{\raggedright}p{2.4cm} >{\raggedright}p{1.5cm} c >{\raggedright}X >{\raggedright}p{2.2cm} >{\raggedright}p{1.3cm} >{\raggedright\arraybackslash}p{2.7cm}@{}}",
           r"\toprule",
           r"Idea & Hypothesis & Spec (ET) & Var. & Headline (95\% CI) & Placebo & Holdout & Verdict \\", r"\midrule"]
    for l in rows:
        c = [x.strip() for x in l.strip().strip("|").split("|")]
        idea, _hyp, spec, _out, var, _sel, head, plac, hold, verdict = c
        h, t = spec.split(" (")
        spec_s = f"\\texttt{{{h}}} {t.rstrip(')').replace(' ET', '')}"
        hold_s = "no" if hold.startswith("no") else ("n/a" if hold.startswith("n/a") else hold.split(":")[0])
        head_s = head.split("; L 0.5")[0].split("; largest")[0]   # first reported setting only
        plac_s = plac
        parts = [x.strip() for x in verdict.split(";")]
        verd = parts[0].split(" (")[0]
        if len(parts) > 1 and parts[1].startswith("corrected"):
            verd += "; " + parts[1]
        out.append(" & ".join(tex_escape(x) if i != 2 else x for i, x in enumerate(
            [idea, SHORT.get(idea, cut(_hyp, 40)).replace("\\ ", " "), spec_s, var, head_s, plac_s, hold_s, verd])) + r" \\")
    out += [r"\bottomrule", r"\end{tabularx}", r"\end{footnotesize}"]
    body = "\n".join(out) + "\n"
    return body.replace("prob.\\textbackslash{} vs", "prob. vs")


def main() -> None:
    p = Keys(); phantom(p); p.write(HERE / "phantom.tex", "Source: " + PHANTOM_REF + " (not merged).")
    e = Keys(); extra(e); e.write(HERE / "extra.tex", "Source: staleline main, committed files.")
    (HERE / "prereg_table.tex").write_text(prereg_table())
    (HERE / "posthoc_table.tex").write_text(posthoc_table())
    meta = {"phantom": [r for r in p.rows], "extra": [r for r in e.rows]}
    (HERE / "generated_keys.json").write_text(json.dumps(meta, indent=1))
    print(f"phantom.tex {len(p.rows)} keys, extra.tex {len(e.rows)} keys, prereg_table.tex, posthoc_table.tex")


if __name__ == "__main__":
    main()
