"""Strategy A capacity on TRAINING (theta 0.80, favorite leg; holdout never loaded).

For every training trade A entered at theta 0.80 (out/strategy_a/rows.parquet), sum the contracts that traded in
that team's own market at or better than A's fill price (own YES price <= fill price) inside A's fill window
[t + 1 s latency, t + 5 min], where t = kickoff - 5 min (strategy_a.decide). The same fill window, latency and
own-market price convention as strategy_a.first_fill / own_market_trades; sizes are added back because
own_market_trades drops them. This is traded volume, not resting depth (no historical Kalshi book): it is an
upper bound on what a taker could have bought at that price in the window without moving it, and it counts both
aggressor sides. Reported per trade (one trade per game): median and IQR, plus the share of trades where it is
below A's 10 contracts.

Reads data/raw/kalshi_only_games.csv, data/raw/kalshi_market_meta.csv, data/raw/kalshi_only/<game_id>.parquet
(training only; asserted) and out/strategy_a/rows.parquet. Writes docs/results/a_capacity.csv (per game) and
docs/results/a_capacity.md. No new variant (no parameter is chosen), so no variants.csv row.

Usage: python scripts/a_capacity.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import run_strategy_a as RA  # noqa: E402
import strategy_a as A  # noqa: E402

ROWS = Path("out/strategy_a/rows.parquet")
OUT_CSV = Path("docs/results/a_capacity.csv")
OUT_MD = Path("docs/results/a_capacity.md")
THETA = 0.80


def own_trades_with_size(trades: pd.DataFrame, g: A.Game, team: str) -> pd.DataFrame:
    t = trades[(trades["market_id"] == f"{g.event}-{team}") & (trades["kind"] == "trade")]
    t = t[["ts", "price", "size"]].sort_values("ts", kind="stable")
    if team == g.away:
        t = t.assign(price=1.0 - t["price"])
    return t.reset_index(drop=True)


def main() -> None:
    rows = pd.read_parquet(ROWS)
    e = rows[(rows["theta"].round(2) == THETA) & ~rows["placebo"].astype(bool) & rows["entered"].astype(bool)]
    games = {g.game_id: g for g in A.load_games(RA.GAMES, RA.META, ticks_dir=RA.TICKS)}
    assert all(g.kickoff < A.SEAL for g in games.values()), "training only"
    out = []
    for r in e.itertuples():
        g = games[r.game_id]
        t_ns = (g.kickoff - pd.Timedelta(seconds=A.ENTRY_BEFORE_KICKOFF_S)).value
        lo, hi = t_ns + int(A.LATENCY_S * A.NS), t_ns + A.FILL_WINDOW_S * A.NS
        tr = own_trades_with_size(pd.read_parquet(RA.TICKS / f"{g.game_id}.parquet"), g, r.team)
        w = tr[(tr["ts"] >= lo) & (tr["ts"] <= hi)]
        # fill_ts is stored as float64 (about 256 ns resolution at this magnitude): match within 1 us
        assert not w.empty and abs(int(w["ts"].iloc[0]) - r.fill_ts) < 1_000, f"fill mismatch {g.game_id}"
        ok = w[w["price"] <= r.fill_price + 1e-9]
        out.append({"game_id": g.game_id, "league": g.league, "team": r.team, "fill_price": r.fill_price,
                    "contracts_at_or_better": float(ok["size"].sum()), "contracts_in_window": float(w["size"].sum()),
                    "trades_at_or_better": len(ok), "trades_in_window": len(w)})
    d = pd.DataFrame(out)
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    d.to_csv(OUT_CSV, index=False)

    lines = ["# Strategy A capacity (training, theta 0.80, favorite leg)", "",
             "Generated by scripts/a_capacity.py. Per A trade (one per game): contracts traded in the team's own "
             "market at or better than A's fill price (own price <= fill price) in A's fill window [t + 1 s, t + 5 "
             "min], t = kickoff - 5 min. Traded volume, not resting depth (no historical Kalshi book), both aggressor "
             "sides: an upper bound on what a taker could buy at that price without moving it.", "",
             "| Group | Trades | Median contracts at or better | IQR | Median contracts in window (any price) | "
             "Share below 10 contracts |", "|---|---|---|---|---|---|"]
    for name, x in [("All", d)] + [(lg, d[d["league"] == lg]) for lg in sorted(d["league"].unique())]:
        q1, med, q3 = np.percentile(x["contracts_at_or_better"], [25, 50, 75])
        lines.append(f"| {name} | {len(x)} | {med:,.0f} | {q1:,.0f} to {q3:,.0f} | "
                     f"{np.median(x['contracts_in_window']):,.0f} | {(x['contracts_at_or_better'] < 10).mean():.3f} |")
    lines += ["", "Caveat: A's fill price is the first in-window trade plus 1 c (half-spread), so almost every trade "
              "in the window is at or better than it; the column is close to total window volume. It spans the whole "
              "5 min window, so it overstates what is available at the single fill instant.",
              "", f"A trades 10 contracts. Check: every trade's first in-window trade equals A's recorded fill_ts "
              f"({len(d)} of {len(d)})."]
    OUT_MD.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
