"""Post-run holdout diagnostics (EXPLORATORY, post-run; they do not change any pre-registered result).

Read-only on the staleline checkout's data/ and results/holdout/ (the one run's frozen outputs); writes only to
results/holdout_diag/ in this checkout. Uses the run's own functions (holdout_mid, xcorr_lead, laggard,
strategy_b, run_strategy_a, run_strategy_b, report_book; identical to RUN_COMMIT 872ff43 except 3 added report
lines in report_book.py that are not used here).

  a  lag distribution, real and placebo, and the full correlation profile of every game (ties, margins)
  d  B: games with median |K - PM| > 0.10 at decision times; prices at kickoff -30/0/+60/+120 min; class
  e  Strategy A trades and skips by league, holdout vs training
  f  Strategy A costs x2 ROC (Webull, Kalshi direct) with CI, run_strategy_a.costs_x2 + boot_ci
  g  laggard latency curves (only latency varies), break-even, daily Sharpe, sample trades
  x  g1 additions from g's saved trades: per-game P&L stats, per-game Sharpe (not annualized), excl. top 5

Usage: PYTHONPATH=. python scripts/holdout_diag.py {a,d,e,f,g} [--staleline ../staleline]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import holdout_mid as H  # noqa: E402
import laggard as L  # noqa: E402
import xcorr_lead as X  # noqa: E402

NS = 1_000_000_000
OUT = ROOT / "results" / "holdout_diag"
README = ("# Holdout diagnostics\n\nexploratory, post-run, does not change any pre-registered result.\n\n"
          "Generated by scripts/holdout_diag.py from the frozen run outputs (results/holdout/ at 5ef528f, RUN_COMMIT "
          "872ff43) and the frozen holdout data; read-only on both.\n")


def ctx(sl: Path):
    vroot, mroot = sl / "data" / "vultr", sl / "data" / "mac"
    machines = {"vultr": H.Machine("vultr", vroot, vroot / "GAPS_vultr.md", vroot / "heartbeats"),
                "mac": H.Machine("mac", sl, mroot / "GAPS_mac.md", mroot / "heartbeats")}
    cands = pd.read_csv(sl / "data" / "live" / "holdout_candidates.csv").set_index("game_id")
    maps = H.load_maps(sl / "data" / "live" / "holdout_maps")
    return machines, cands, maps


def inst(cands, maps, gid):
    return H.instruments(cands.loc[[gid]].reset_index().iloc[0], maps)


def corr_profile(tk, to, other, exc, max_lag=X.MAX_LAG_S) -> dict:
    """Same lines as xcorr_lead.game_lag_mid, returning the whole correlation profile."""
    gx, gy = X.mid_grid(X.mid_snapshots(tk, "kalshi")), X.mid_grid(X.mid_snapshots(to, other))
    if gx.empty or gy.empty:
        return {}
    lo, hi = max(gx.index.min(), gy.index.min()), min(gx.index.max(), gy.index.max())
    if hi - lo + 1 < 2 * max_lag + 2:
        return {}
    idx = np.arange(lo, hi + 1, dtype="int64")
    rx, ry = X.mid_changes(gx, exc).reindex(idx), X.mid_changes(gy, exc).reindex(idx)
    corr = {lag: float(rx.corr(ry.shift(-lag))) for lag in range(-max_lag, max_lag + 1)}
    n_pairs = {lag: int((rx.notna() & ry.shift(-lag).notna()).sum()) for lag in (-1, 0, 1)}
    nz = {lag: int(((rx.abs() > 1e-12) & (ry.shift(-lag).abs() > 1e-12)).sum()) for lag in (-1, 0, 1)}
    return {"corr": corr, "pairs": n_pairs, "both_moved": nz}


def summarize_profile(p: dict) -> dict:
    c = {k: (v if v == v else -np.inf) for k, v in p["corr"].items()}
    lag = max(c, key=c.get)                         # the run's choice: first maximal key in order -15 .. +15
    best = c[lag]
    ties = sorted(k for k, v in c.items() if np.isfinite(best) and abs(v - best) <= 1e-12)
    rest = sorted((v for k, v in c.items() if k not in ties), reverse=True)
    neg = max((v for k, v in c.items() if k < 0), default=-np.inf)
    return {"lag_s": float(lag) if np.isfinite(best) else np.nan, "corr_best": best, "n_tied_lags": len(ties),
            "tied_lags": " ".join(map(str, ties)), "margin_to_next": best - rest[0] if rest else np.nan,
            "corr_lag0": c.get(0), "corr_best_negative": neg, "n_nan_lags": sum(1 for v in p["corr"].values() if v != v),
            "pairs_lag0": p["pairs"][0], "both_moved_lag0": p["both_moved"][0], "both_moved_lag-1": p["both_moved"][-1],
            "both_moved_lag+1": p["both_moved"][1]}


def part_a(sl: Path) -> None:
    machines, cands, maps = ctx(sl)
    res = sl / "results" / "holdout"
    rows = []
    for test, (other, _) in H.TESTS.items():
        pg = pd.read_csv(res / f"lead_{test}_per_game.csv")
        q = pg[pg["qualifying"].fillna(False).astype(bool)]
        for r in q.itertuples():
            m, i = machines[r.machine], inst(cands, maps, r.game_id)
            lo, end = int(r.window_start_ns), int(r.window_end_ns)
            tk = m.rows("kalshi", i["kalshi"], lo, end)
            to = m.rows(other, i[other], lo, end)
            tk, to = tk[(tk.ts >= lo) & (tk.ts < end)], to[(to.ts >= lo) & (to.ts < end)]
            p = corr_profile(tk, to, other, [(int(r.excl_lo_g), int(r.excl_hi_g))])
            s = summarize_profile(p) if p else {"lag_s": np.nan}
            rows.append({"test": test, "kind": "real", "game": r.game_id, "recorded_lag_s": r.lag_s, **s,
                         **{f"c{k:+d}": v for k, v in (p.get("corr") or {}).items()}})
        pl = pd.read_csv(res / f"lead_{test}_placebo.csv")
        for r in pl.itertuples():
            a = q[q.game_id == r.game_a].iloc[0]
            m = machines[r.machine]
            lo, end = int(a.window_start_ns), int(a.window_end_ns)
            tk = m.rows("kalshi", inst(cands, maps, r.game_a)["kalshi"], lo, end - 1)
            to = m.rows(other, inst(cands, maps, r.game_b)[other], lo, end - 1)
            p = corr_profile(tk, to, other, [(int(a.excl_lo_g), int(a.excl_hi_g))]) if len(tk) and len(to) else {}
            s = summarize_profile(p) if p else {"lag_s": np.nan}
            rows.append({"test": test, "kind": "placebo", "game": f"{r.game_a}|{r.game_b}", "recorded_lag_s": r.lag_s,
                         **s, **{f"c{k:+d}": v for k, v in (p.get("corr") or {}).items()}})
        print(f"{test}: done", flush=True)
    d = pd.DataFrame(rows)
    d.to_csv(OUT / "a_corr_profiles.csv", index=False)
    match = (d["lag_s"].fillna(-99) == d["recorded_lag_s"].fillna(-99))
    lags = range(-15, 16)
    dist = []
    for (t, k), x in d.groupby(["test", "kind"]):
        vc = x["recorded_lag_s"].dropna().astype(int).value_counts()
        dist.append({"test": t, "kind": k, "n": int(x["recorded_lag_s"].notna().sum()),
                     **{f"{l:+d}": int(vc.get(l, 0)) for l in lags}})
    pd.DataFrame(dist).to_csv(OUT / "a_lag_distribution.csv", index=False)
    summ = []
    for (t, k), x in d.groupby(["test", "kind"]):
        x = x[x["recorded_lag_s"].notna()]
        summ.append({"test": t, "kind": k, "n": len(x), "recomputed_lag_matches_recorded": int(match[x.index].sum()),
                     "games_with_tied_max": int((x["n_tied_lags"] > 1).sum()),
                     "games_lag0": int((x["recorded_lag_s"] == 0).sum()),
                     "median_margin_to_next": float(x["margin_to_next"].median()),
                     "median_corr_lag0": float(x["corr_lag0"].median()),
                     "median_corr_best_negative": float(x["corr_best_negative"].median()),
                     "median_both_moved_lag0": float(x["both_moved_lag0"].median()),
                     "median_both_moved_lag-1": float(x["both_moved_lag-1"].median()),
                     "median_both_moved_lag+1": float(x["both_moved_lag+1"].median())})
    pd.DataFrame(summ).to_csv(OUT / "a_summary.csv", index=False)
    print(pd.DataFrame(dist).to_string(index=False))
    print(pd.DataFrame(summ).T.to_string())


# ---------- d ----------

D_RULE = ("Classification (fixed before looking at any of the 25 games): MISMATCH if at >= 3 of the 4 checkpoints "
          "(kickoff -30/0/+60/+120 min) both prices exist, |K - PM| > 0.20 and |K - (1 - PM)| < 0.05. Else STALE "
          "VENUE if, at the game's B decision times, the median age of the last trade on one venue is > 120 s "
          "(that venue named). Else REAL DISAGREEMENT.")


def part_d(sl: Path) -> None:
    import b_orientation_check as BO  # noqa: E402  (scripts/, rule fixed in 0014b1e)
    import run_strategy_b as RSB
    import strategy_b as B
    res, hr = sl / "results" / "holdout", sl / "data" / "holdout_raw"
    t = pd.read_parquet(res / "strategy_b_trades.parquet")
    chk = BO.run(t, hr / "kalshi", hr / "polymarket", "{}.parquet", "{}.parquet")
    e = chk[chk["evaluable"].astype(bool)]
    big = e[e["median_abs_diff"] > 0.10].sort_values("median_abs_diff", ascending=False)
    ev = pd.read_csv(hr / "events.csv").set_index("game_id")
    pm = pd.read_csv(hr / "pm_map.csv").set_index("game_id")
    rows = []
    for g in big.itertuples():
        kt, pt = pd.read_parquet(hr / "kalshi" / f"{g.game_id}.parquet"), pd.read_parquet(hr / "polymarket" / f"{g.game_id}.parquet")
        ko_g = pd.Timestamp(ev.loc[g.game_id, "espn_kickoff"]).value // NS
        sel = t[(t.game_id == g.game_id) & (t.k == 0.05) & (t.m == 10) & (t["T"] == 300)]
        dec = np.sort(np.concatenate([sel.entry_dec_ns.to_numpy("int64"), sel.exit_dec_ns.to_numpy("int64")])) // NS - 1
        lo_g, hi_g = int(min(dec.min(), ko_g - 1800)), int(max(dec.max(), ko_g + 7200))
        kp, _ = B.venue_grid(kt, "kalshi", lo_g, hi_g)
        pp, _ = B.venue_grid(pt, "polymarket", lo_g, hi_g)
        row = {"game_id": g.game_id, "league": ev.loc[g.game_id, "league"], "pm_slug": pm.loc[g.game_id, "pm_slug"],
               "pm_outcomes (away, home)": f"{pm.loc[g.game_id, 'pm_away']} / {pm.loc[g.game_id, 'pm_home']}",
               "kalshi (away, home)": f"{ev.loc[g.game_id, 'k_away']} / {ev.loc[g.game_id, 'k_home']}",
               "pm_flipped": bool(pm.loc[g.game_id, "pm_flipped"]), "median_abs_diff": g.median_abs_diff,
               "n_decisions": g.n_decisions}
        mm = 0
        for name, off in (("ko-30", -1800), ("ko", 0), ("ko+60", 3600), ("ko+120", 7200)):
            k, p = kp[ko_g + off - lo_g], pp[ko_g + off - lo_g]
            row[f"K_{name}"], row[f"PM_{name}"] = round(float(k), 4), round(float(p), 4)
            if k == k and p == p and abs(k - p) > 0.20 and abs(k - (1 - p)) < 0.05:
                mm += 1
        ages = {}
        for v, tr in (("kalshi", kt), ("polymarket", pt)):
            ts = np.sort(tr.loc[tr["kind"] == "trade", "ts"].to_numpy("int64")) // NS if "kind" in tr else np.sort(tr["ts"].to_numpy("int64")) // NS
            j = np.searchsorted(ts, dec, side="right") - 1
            a = np.where(j >= 0, dec - ts[np.clip(j, 0, None)], np.nan)
            ages[v] = float(np.nanmedian(a)) if len(a) else np.nan
        row.update(median_last_trade_age_s_kalshi=ages["kalshi"], median_last_trade_age_s_pm=ages["polymarket"])
        if mm >= 3:
            row["class"] = "mismatch"
        elif max(ages.values()) > 120:
            row["class"] = f"stale venue ({max(ages, key=ages.get)})"
        else:
            row["class"] = "real disagreement"
        rows.append(row)
    d = pd.DataFrame(rows)
    d.to_csv(OUT / "d_b_big_diff_games.csv", index=False)
    f_all = t[(t.k == 0.05) & (t.m == 10) & (t["T"] == 300)]
    n_games = int(pd.read_csv(res / "strategy_b_summary.csv")["games"].iloc[0])
    s_all = RSB.summarize(f_all, n_games).assign(sample="all (reproduces strategy_b_summary.csv)")
    s_ex = RSB.summarize(f_all[~f_all.game_id.isin(d.game_id)], n_games - len(d)).assign(
        sample=f"excluding the {len(d)} games with median |K - PM| > 0.10 (EXPLORATORY)")
    s = pd.concat([s_all, s_ex], ignore_index=True)
    s.to_csv(OUT / "d_b_excluding.csv", index=False)
    (OUT / "d_rule.txt").write_text(D_RULE + "\n")
    pd.set_option("display.width", 250)
    print(D_RULE)
    print(d.to_string(index=False))
    print(s[["sample", "games", "n_trades", "edge_webull_cents", "edge_webull_ci_lo", "edge_webull_ci_hi",
             "edge_direct_cents", "edge_direct_ci_lo", "edge_direct_ci_hi"]].to_string(index=False))


# ---------- e, f ----------

def part_e(sl: Path) -> None:
    import run_strategy_a as RA
    out = []
    for name, p in (("holdout", sl / "results" / "holdout" / "strategy_a_rows.parquet"),
                    ("training", sl / "out" / "strategy_a" / "rows.parquet")):
        r = pd.read_parquet(p)
        r = r[(r["theta"].round(2) == 0.80) & ~r["placebo"].astype(bool)]
        for lg, x in r.groupby("league"):
            sk = x["skip"].fillna("").astype(str)
            row = {"sample": name, "league": lg, "games": len(x), "trades": int(x["entered"].astype(bool).sum())}
            for nm, f in RA.SKIPS:
                row[f"skip_{nm}"] = int(f(sk).sum())
            out.append(row)
    d = pd.DataFrame(out)
    d.to_csv(OUT / "e_a_by_league.csv", index=False)
    print(d.to_string(index=False))


def part_f(sl: Path) -> None:
    import run_strategy_a as RA
    out = []
    for name, p in (("holdout", sl / "results" / "holdout" / "strategy_a_rows.parquet"),
                    ("training (check: must equal out/strategy_a/selected_theta_checks.csv)", sl / "out" / "strategy_a" / "rows.parquet")):
        r = pd.read_parquet(p)
        e = r[(r["theta"].round(2) == 0.80) & ~r["placebo"].astype(bool) & r["entered"].astype(bool)]
        x2 = RA.costs_x2(e)
        for line in ("webull", "direct"):
            x = x2[f"roc_{line}"].to_numpy(float)
            lo, hi = RA.boot_ci(x, np.random.default_rng(RA.SEED))
            out.append({"sample": name, "line": line, "n": len(x), "roc_mean": x.mean(), "ci_lo": lo, "ci_hi": hi,
                        "pnl_total": x2[f"pnl_{line}"].sum()})
    d = pd.DataFrame(out)
    d.to_csv(OUT / "f_a_costs_x2_roc.csv", index=False)
    print("function: run_strategy_a.costs_x2 (fees x2, fill + 1 c, same cap) + run_strategy_a.boot_ci "
          "(game bootstrap, 2,000, seed 20261003), as run_strategy_a.main for the training line")
    print(d.to_string(index=False))


# ---------- g ----------

G_ADDED = (0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 7.5, 10.0)


def part_g(sl: Path) -> None:
    import report_book as RB
    sys.path.insert(0, str(ROOT / "scripts"))
    import final_test_run as F                       # rows_with_size: the run's own loader
    machines, cands, maps = ctx(sl)
    res = sl / "results" / "holdout"
    delays = L.load_seconds_delay(sl / "data" / "live" / "holdout_seconds_delay.csv")
    trades = []
    for test, (other, _) in H.TESTS.items():
        pg = pd.read_csv(res / f"lead_{test}_per_game.csv")
        q = pg[pg["qualifying"].fillna(False).astype(bool)]
        for r in q.itertuples():
            m, i = machines[r.machine], inst(cands, maps, r.game_id)
            lo = int(r.window_start_ns)
            pin = None if pd.isna(r.pin_start_g) else int(r.pin_start_g)
            hi = L.trading_end_ns(pd.Timestamp(r.kickoff_utc).value, pin)
            kt = F.rows_with_size(m, "kalshi", i["kalshi"], lo - 3600 * NS, hi + 120 * NS)
            ot = F.rows_with_size(m, other, i[other], lo - 3600 * NS, hi + 120 * NS)
            gaps = m.gaps()
            outs = [(int(g.start_ns), int(g.end_ns)) for g in gaps[gaps["venue"].isin(["kalshi", other, "all"])].itertuples()
                    if g.end_ns > lo and g.start_ns < hi]
            cond = (maps["polymarket_com"].get(cands.loc[r.game_id, "kalshi_ticker"]) or {}).get("condition")
            tr = L.evaluate_game(r.game_id, r.kickoff_utc, kt, ot, other, lo, hi,
                                 exclude=[(int(r.excl_lo_g), int(r.excl_hi_g))], outages=outs, holdout_run=True,
                                 condition=cond if other == "polymarket" else None, delays=delays, latencies=G_ADDED)
            if len(tr):
                trades.append(tr.assign(test=test, machine=r.machine))
        print(f"{test}: done", flush=True)
    t = pd.concat(trades, ignore_index=True)
    t.to_parquet(OUT / "g_laggard_trades.parquet", index=False)
    # check: the run's latencies reproduce the committed curve exactly
    run_curve = pd.read_csv(res / "laggard_latency_curve.csv")
    curve = pd.concat([L.latency_curve(d).assign(venue=v) for v, d in t.groupby("venue")], ignore_index=True)
    days = pd.date_range("2026-08-06", "2026-10-04", freq="D")     # OOS season days (numbers.json OOS.season_*)
    sharpe = []
    for (v, lat), d in t[t["filled"].astype(bool)].groupby(["venue", "latency_s"]):
        b = pd.DataFrame({"day": pd.to_datetime(d["entry_fill_ns"], unit="ns", utc=True).dt.tz_convert("America/New_York").dt.date,
                          "pnl_webull": d["pnl_cents"] / 100, "contracts": d["qty"], "notional": d["qty"] * d["entry_px"]})
        pnl = RB.daily(b, days)
        mt = RB.metrics(pnl, 1.0, b)
        sharpe.append({"venue": v, "latency_s": lat, "sharpe_x365_season_days": mt["sharpe"],
                       "days_with_trades": int((pnl != 0).sum()), "season_days": len(pnl)})
    curve = curve.merge(pd.DataFrame(sharpe), on=["venue", "latency_s"], how="left")
    curve.to_csv(OUT / "g_latency_curves.csv", index=False)
    chk = run_curve.merge(curve, on=["venue", "latency_s"], suffixes=("_run", "_diag"))
    chk = chk.assign(same_n=chk.n_trades_run == chk.n_trades_diag,
                     same_mean=(chk.edge_cents_mean_run - chk.edge_cents_mean_diag).abs() < 1e-9,
                     same_ci=((chk.edge_ci_low_run - chk.edge_ci_low_diag).abs() < 1e-9)
                     & ((chk.edge_ci_high_run - chk.edge_ci_high_diag).abs() < 1e-9))
    chk[["venue", "latency_s", "same_n", "same_mean", "same_ci"]].to_csv(OUT / "g_check_vs_run.csv", index=False)
    be = []
    for v, c in curve.groupby("venue"):
        c = c.sort_values("latency_s")
        pos = c[c["edge_ci_low"] > 0]
        cross = None
        for (l0, m0), (l1, m1) in zip(c[["latency_s", "edge_cents_mean"]].values[:-1], c[["latency_s", "edge_cents_mean"]].values[1:]):
            if m0 > 0 >= m1:
                cross = l0 + (l1 - l0) * m0 / (m0 - m1)
                break
        be.append({"venue": v, "largest_latency_ci_low_above_0": float(pos["latency_s"].max()) if len(pos) else None,
                   "mean_crosses_0_at_s (linear interp.)": cross,
                   "mean_positive_at_all_latencies": bool((c["edge_cents_mean"] > 0).all()),
                   "mean_negative_at_all_latencies": bool((c["edge_cents_mean"] < 0).all())})
    pd.DataFrame(be).to_csv(OUT / "g_break_even.csv", index=False)
    # g5: 5 random filled Polymarket US trades at total latency 1 s, with the quote actually used
    f = t[(t.venue == "polymarket_us") & (t.latency_s == 1.0) & t["filled"].astype(bool)].sample(5, random_state=20261003)
    out = []
    for r in f.itertuples():
        m, i = machines[r.machine], inst(cands, maps, r.game_id)
        q = L.book(F.rows_with_size(m, "polymarket_us", i["polymarket_us"], int(r.entry_g) * NS - 3600 * NS, r.exit_fill_ns), "polymarket_us")
        kq = F.rows_with_size(m, "kalshi", i["kalshi"], (r.entry_g - 15) * NS, (r.entry_g + 1) * NS)
        km = X.mid_grid(X.mid_snapshots(kq, "kalshi"))
        dec_ns = (int(r.entry_g) + 1) * NS
        side = "ask" if r.direction > 0 else "bid"
        qi = q[q["ts"] <= r.entry_fill_ns].iloc[-1]
        xi = q[q["ts"] <= r.exit_fill_ns].iloc[-1]
        out.append({"game_id": r.game_id, "decision_time_et": pd.Timestamp(dec_ns, tz="UTC").tz_convert("America/New_York").strftime("%H:%M:%S"),
                    "direction": int(r.direction),
                    "kalshi_mid_g-10 (illustrative)": float(km.get(int(r.entry_g) - 10, np.nan)), "kalshi_mid_g (illustrative)": float(km.get(int(r.entry_g), np.nan)),
                    "fill_time_minus_decision_s": (r.entry_fill_ns - dec_ns) / NS,
                    "quote_used_received_minus_decision_s": (int(qi.ts) - dec_ns) / NS,
                    "quote_used_received_minus_fill_time_s": (int(qi.ts) - r.entry_fill_ns) / NS,
                    "pmus_bid": float(qi.bid), "pmus_ask": float(qi.ask), "entry_px": r.entry_px, "fee_entry": r.fee_entry,
                    "exit_reason": r.exit_reason, "exit_px": r.exit_px, "fee_exit": r.fee_exit,
                    "exit_quote_received_minus_exit_fill_s": (int(xi.ts) - r.exit_fill_ns) / NS, "net_cents": r.pnl_cents,
                    "net_cents_per_contract": r.edge_cents_per_contract})
    pd.DataFrame(out).to_csv(OUT / "g5_sample_trades.csv", index=False)
    allf = t[(t.venue == "polymarket_us") & (t.latency_s == 1.0) & t["filled"].astype(bool)]
    pd.set_option("display.width", 250)
    print(curve[["venue", "latency_s", "n_trades", "n_games", "edge_cents_mean", "edge_ci_low", "edge_ci_high",
                 "sharpe_x365_season_days", "days_with_trades"]].to_string(index=False))
    print(pd.DataFrame(be).to_string(index=False))
    print("check vs run:", chk[["same_n", "same_mean", "same_ci"]].all().to_dict(), f"({len(chk)} shared points)")
    print(pd.DataFrame(out).T.to_string())
    print(f"all {len(allf)} PM US fills at 1 s: fill_ns - decision_ns min {((allf.entry_fill_ns - (allf.entry_g + 1) * NS) / NS).min():.3f} s")


def part_x(sl: Path) -> None:
    """g1 additions (post-step on g's saved trades, nothing recomputed): per latency point and venue, per-game
    net P&L stats, per-game Sharpe (mean / sd of per-game net P&L, NOT annualized), concentration."""
    t = pd.read_parquet(OUT / "g_laggard_trades.parquet")
    f = t[t["filled"].astype(bool)]
    rows = []
    for (v, lat), d in f.groupby(["venue", "latency_s"]):
        g = d.groupby("game_id").agg(pnl=("pnl_cents", "sum"), n=("pnl_cents", "size"),
                                     contracts=("qty", "sum"))
        g["pnl"] = g["pnl"] / 100                                    # dollars
        top5 = g.nlargest(5, "pnl").index
        rest = d[~d["game_id"].isin(top5)]
        sd = g["pnl"].std(ddof=1)
        rows.append({"venue": v, "latency_s": lat, "n_games_with_trade": len(g), "n_trades": len(d),
                     "per_game_pnl_mean_usd": g["pnl"].mean(), "per_game_pnl_median_usd": g["pnl"].median(),
                     "per_game_pnl_sd_usd": sd, "share_games_pnl_positive": float((g["pnl"] > 0).mean()),
                     "per_game_sharpe_not_annualized": g["pnl"].mean() / sd if sd > 0 else np.nan,
                     "net_c_per_contract_excl_top5_games": float(rest["edge_cents_per_contract"].mean()),
                     "n_trades_excl_top5": len(rest)})
    import report_book as RB
    days = pd.date_range("2026-08-06", "2026-10-04", freq="D")     # OOS season days (numbers.json OOS.season_*)
    sh = []
    for (v, lat), d in f.groupby(["venue", "latency_s"]):
        # day = exit fill time (ET), as report_book's books close on the exit (report_book.py:61)
        b = pd.DataFrame({"day": pd.to_datetime(d["exit_fill_ns"], unit="ns", utc=True).dt.tz_convert("America/New_York").dt.date,
                          "pnl_webull": d["pnl_cents"] / 100, "contracts": d["qty"], "notional": d["qty"] * d["entry_px"]})
        pnl = RB.daily(b, days)
        sh.append({"venue": v, "latency_s": lat, "sharpe_x365_season_days": RB.metrics(pnl, 1.0, b)["sharpe"],
                   "days_with_trades": int((pnl != 0).sum())})
    c = pd.read_csv(OUT / "g_latency_curves.csv").drop(columns=["sharpe_x365_season_days", "days_with_trades"], errors="ignore")
    c = c.merge(pd.DataFrame(sh), on=["venue", "latency_s"], how="left")
    c.to_csv(OUT / "g_latency_curves.csv", index=False)
    out = c.merge(pd.DataFrame(rows), on=["venue", "latency_s", "n_trades"], how="left")
    out["sharpe_x365_season_days"] = out["sharpe_x365_season_days"].map(lambda x: f"{x:.3f} (degenerate, one day, not reported)")
    out.to_csv(OUT / "g1_latency_table.csv", index=False)
    pd.set_option("display.width", 300)
    print(out[["venue", "latency_s", "n_trades", "n_games_with_trade", "edge_cents_mean", "edge_ci_low", "edge_ci_high",
               "per_game_pnl_mean_usd", "per_game_pnl_median_usd", "per_game_pnl_sd_usd", "share_games_pnl_positive",
               "per_game_sharpe_not_annualized", "net_c_per_contract_excl_top5_games", "sharpe_x365_season_days"]].to_string(index=False))


def part_y(sl: Path) -> None:
    """g5 alone, from g's saved trades (reviewer fixes: quote lookup from window start - 1 h; Kalshi mids illustrative)."""
    sys.path.insert(0, str(ROOT / "scripts"))
    import final_test_run as F
    machines, cands, maps = ctx(sl)
    t = pd.read_parquet(OUT / "g_laggard_trades.parquet")
    # g5: 5 random filled Polymarket US trades at total latency 1 s, with the quote actually used
    f = t[(t.venue == "polymarket_us") & (t.latency_s == 1.0) & t["filled"].astype(bool)].sample(5, random_state=20261003)
    out = []
    for r in f.itertuples():
        m, i = machines[r.machine], inst(cands, maps, r.game_id)
        q = L.book(F.rows_with_size(m, "polymarket_us", i["polymarket_us"], int(r.entry_g) * NS - 3600 * NS, r.exit_fill_ns), "polymarket_us")
        kq = F.rows_with_size(m, "kalshi", i["kalshi"], (r.entry_g - 15) * NS, (r.entry_g + 1) * NS)
        km = X.mid_grid(X.mid_snapshots(kq, "kalshi"))
        dec_ns = (int(r.entry_g) + 1) * NS
        side = "ask" if r.direction > 0 else "bid"
        qi = q[q["ts"] <= r.entry_fill_ns].iloc[-1]
        xi = q[q["ts"] <= r.exit_fill_ns].iloc[-1]
        out.append({"game_id": r.game_id, "decision_time_et": pd.Timestamp(dec_ns, tz="UTC").tz_convert("America/New_York").strftime("%H:%M:%S"),
                    "direction": int(r.direction),
                    "kalshi_mid_g-10 (illustrative)": float(km.get(int(r.entry_g) - 10, np.nan)), "kalshi_mid_g (illustrative)": float(km.get(int(r.entry_g), np.nan)),
                    "fill_time_minus_decision_s": (r.entry_fill_ns - dec_ns) / NS,
                    "quote_used_received_minus_decision_s": (int(qi.ts) - dec_ns) / NS,
                    "quote_used_received_minus_fill_time_s": (int(qi.ts) - r.entry_fill_ns) / NS,
                    "pmus_bid": float(qi.bid), "pmus_ask": float(qi.ask), "entry_px": r.entry_px, "fee_entry": r.fee_entry,
                    "exit_reason": r.exit_reason, "exit_px": r.exit_px, "fee_exit": r.fee_exit,
                    "exit_quote_received_minus_exit_fill_s": (int(xi.ts) - r.exit_fill_ns) / NS, "net_cents": r.pnl_cents,
                    "net_cents_per_contract": r.edge_cents_per_contract})
    pd.DataFrame(out).to_csv(OUT / "g5_sample_trades.csv", index=False)
    allf = t[(t.venue == "polymarket_us") & (t.latency_s == 1.0) & t["filled"].astype(bool)]
    pd.set_option("display.width", 250)
    print(pd.DataFrame(out).T.to_string())
    d = (allf.entry_fill_ns - (allf.entry_g + 1) * NS) / NS
    print(f"all {len(allf)} PM US fills at 1 s: fill time - decision time min {d.min():.3f} s, max {d.max():.3f} s")


H0_NOTE = ("Caveat: the collector writes a Polymarket US row only when that market's top of book changes "
           "(collector/run.py PolymarketUS._rows), so a gap between recorded snapshots is time between quote CHANGES "
           "(no-change polls and failed polls are both invisible), and snapshot age at a fill is time since the last "
           "recorded change, not time since the last poll.")


def part_h(sl: Path) -> None:
    """h0: Polymarket US snapshot gaps per game window, snapshot age at 1 s laggard fills, results split by age,
    lead-test lags split by window p90 gap. Our data only, no network."""
    sys.path.insert(0, str(ROOT / "scripts"))
    import final_test_run as F
    machines, cands, maps = ctx(sl)
    res = sl / "results" / "holdout"
    pg = pd.read_csv(res / "lead_Polymarket US_per_game.csv")
    q = pg[pg["qualifying"].fillna(False).astype(bool)]
    lt = pd.read_csv(res / "laggard_trades.csv")
    f1 = lt[(lt.venue == "polymarket_us") & (lt.latency_s == 1.0) & lt["filled"].astype(bool)].copy()
    gaps, ages = [], []
    for r in q.itertuples():
        m, i = machines[r.machine], inst(cands, maps, r.game_id)
        lo, end = int(r.window_start_ns), int(r.window_end_ns)
        rows = F.rows_with_size(m, "polymarket_us", i["polymarket_us"], lo - 3600 * NS, end + 3600 * NS)
        b = L.book(rows, "polymarket_us")
        ts = b["ts"].to_numpy("int64")
        w = ts[(ts >= lo) & (ts < end)]
        d = np.diff(w) / NS
        gaps.append({"game_id": r.game_id, "machine": r.machine, "n_snapshots": len(w),
                     "gap_median_s": float(np.median(d)) if len(d) else np.nan,
                     "gap_p90_s": float(np.quantile(d, 0.9)) if len(d) else np.nan,
                     "gap_p99_s": float(np.quantile(d, 0.99)) if len(d) else np.nan,
                     "gap_max_s": float(d.max()) if len(d) else np.nan,
                     "share_gaps_gt_2s": float((d > 2).mean()) if len(d) else np.nan, "lag_s": r.lag_s})
        for x in f1[f1.game_id == r.game_id].itertuples():
            je = np.searchsorted(ts, x.entry_fill_ns, side="right") - 1
            jx = np.searchsorted(ts, x.exit_fill_ns, side="right") - 1
            ages.append({"idx": x.Index, "entry_snapshot_age_s": (x.entry_fill_ns - ts[je]) / NS if je >= 0 else np.nan,
                         "exit_snapshot_age_s": (x.exit_fill_ns - ts[jx]) / NS if jx >= 0 else np.nan})
    G = pd.DataFrame(gaps)
    G.to_csv(OUT / "h0_snapshot_gaps_per_game.csv", index=False)
    A = pd.DataFrame(ages).set_index("idx")
    f1 = f1.join(A)
    f1[["game_id", "entry_fill_ns", "exit_fill_ns", "entry_snapshot_age_s", "exit_snapshot_age_s",
        "edge_cents_per_contract", "pnl_cents"]].to_csv(OUT / "h0_fill_snapshot_ages.csv", index=False)

    def q_(x):
        x = x.dropna()
        return {"n": len(x), "median": x.median(), "p90": x.quantile(0.9), "p99": x.quantile(0.99), "max": x.max(),
                "share_gt_1.5s": float((x > 1.5).mean()), "share_gt_5s": float((x > 5).mean())}
    age_dist = pd.DataFrame({"entry": q_(f1["entry_snapshot_age_s"]), "exit": q_(f1["exit_snapshot_age_s"])}).T

    def stats(d):
        g = d.groupby("game_id")
        lo, hi = L.game_bootstrap_ci(g["edge_cents_per_contract"].sum().to_numpy(), g.size().to_numpy())
        top5 = g["pnl_cents"].sum().nlargest(5).index
        return {"n_fills": len(d), "n_games": g.ngroups, "mean_net_c_per_contract": d["edge_cents_per_contract"].mean(),
                "ci_lo": lo, "ci_hi": hi, "share_games_pnl_positive": float((g["pnl_cents"].sum() > 0).mean()),
                "mean_excl_top5_games": d[~d.game_id.isin(top5)]["edge_cents_per_contract"].mean()}
    fresh = f1[(f1.entry_snapshot_age_s <= 1.5) & (f1.exit_snapshot_age_s <= 1.5)]
    split = pd.DataFrame([{"sample": "all 1 s fills (run)", **stats(f1)},
                          {"sample": "both snapshot ages <= 1.5 s (EXPLORATORY)", **stats(fresh)},
                          {"sample": "rest (EXPLORATORY)", **stats(f1.drop(fresh.index))}])
    split.to_csv(OUT / "h0_laggard_by_snapshot_age.csv", index=False)
    G["p90_le_1.5"] = G["gap_p90_s"] <= 1.5
    lead = G.groupby("p90_le_1.5").agg(n_games=("lag_s", "size"), median_lag_s=("lag_s", "median"),
                                       share_positive=("lag_s", lambda x: float((x > 0).mean()))).reset_index()
    lead.to_csv(OUT / "h0_lead_by_window_gap.csv", index=False)
    allg = np.concatenate([[]])
    (OUT / "h0_note.txt").write_text(H0_NOTE + "\n")
    pd.set_option("display.width", 250)
    print(H0_NOTE)
    print("per-game window gap stats, distribution over the", len(G), "qualifying Polymarket US games:")
    print(G[["n_snapshots", "gap_median_s", "gap_p90_s", "gap_p99_s", "gap_max_s", "share_gaps_gt_2s"]].describe(percentiles=[.1, .5, .9]).T.to_string())
    print("snapshot age at 1 s fills:"); print(age_dist.to_string())
    print(split.to_string(index=False))
    print("lead test, Polymarket US, by window p90 snapshot gap <= 1.5 s (report only; decision unchanged):")
    print(lead.to_string(index=False))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("part", choices=list("adefghxy"))
    ap.add_argument("--staleline", type=Path, default=ROOT.parent / "staleline")
    a = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "README.md").write_text(README)
    {"a": part_a, "d": part_d, "e": part_e, "f": part_f, "g": part_g, "h": part_h, "x": part_x, "y": part_y}[a.part](a.staleline.resolve())


if __name__ == "__main__":
    main()
