"""Generate paper/numbers.tex: one \\defval{key}{value} per number (generated, never hand-written).

Sources: results/numbers.json (training keys and the run's OOS keys, as written by the run), results/holdout/
numbers.json (the one run's own copy; its keys are prefixed oos_run_), results/holdout_diag/numbers_diag.json
(exploratory, post-run; keys prefixed diag_), results/posthoc/numbers_posthoc.json (post-hoc, exploratory;
keys already prefixed posthoc_; read only if present). Nested values (lists, dicts) are flattened with "_" (lists: _0, _1).
Key characters other than letters and digits become "_"; the exact source key is kept in a comment.

Usage: python scripts/make_numbers_tex.py
"""
from __future__ import annotations

import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "numbers.tex"


def fmt(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return f"{v:,}".replace(",", "{,}")
    if isinstance(v, float):
        if not math.isfinite(v):
            return "n/a"
        a = abs(v)
        s = f"{v:.3g}" if (a and a < 1e-3) or a >= 1e6 else (f"{v:.4f}" if a < 10 else f"{v:,.1f}".replace(",", "{,}"))
        return s.replace("e-0", "e-").replace("e+0", "e+")
    s = str(v)
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("%", r"\%"), ("&", r"\&"), ("#", r"\#"), ("$", r"\$")):
        s = s.replace(a, b)
    return s


def flat(prefix: str, v, out: list) -> None:
    if isinstance(v, dict) and set(v) >= {"value", "source"}:
        flat(prefix, v["value"], out)
    elif isinstance(v, dict):
        for k, x in v.items():
            flat(f"{prefix}_{k}" if prefix else k, x, out)
    elif isinstance(v, list):
        for i, x in enumerate(v):
            flat(f"{prefix}_{i}", x, out)
    else:
        out.append((prefix, v))


def tex_key(k: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", k).strip("_")


def main() -> None:
    rows = []
    for path, pre in (("results/numbers.json", ""), ("results/holdout/numbers.json", "oos_run_"),
                      ("results/holdout_diag/numbers_diag.json", "diag_"),
                      ("results/posthoc/numbers_posthoc.json", "")):
        if path.startswith("results/posthoc/") and not (ROOT / path).exists():
            continue
        d = json.loads((ROOT / path).read_text())
        if pre == "diag_":
            d = d["numbers"]
        items = []
        flat("", d, items)
        rows += [(pre + k, k, v, path) for k, v in items]
    seen, lines = {}, ["% GENERATED by scripts/make_numbers_tex.py; do not edit by hand.",
                       "% diag_ keys: exploratory, post-run (results/holdout_diag/numbers_diag.json).",
                       "% posthoc_ keys: post-hoc, exploratory (results/posthoc/numbers_posthoc.json).",
                       r"\providecommand{\defval}[2]{\expandafter\def\csname val@#1\endcsname{#2}}"]
    for key, src_key, v, path in rows:
        tk = tex_key(key)
        if tk in seen:
            raise SystemExit(f"key collision: {tk} from {path}:{src_key} and {seen[tk]}")
        seen[tk] = f"{path}:{src_key}"
        lines.append(f"\\defval{{{tk}}}{{{fmt(v)}}}  % {path}: {src_key}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT.relative_to(ROOT)}: {len(seen)} keys "
          f"({sum(k.startswith('diag_') for k in seen)} diag_, {sum(k.startswith('oos_run_') for k in seen)} oos_run_, "
          f"{sum(k.startswith('posthoc_') for k in seen)} posthoc_)")


if __name__ == "__main__":
    main()
