"""Strategy A taker vs A-maker side by side on TRAINING (exploratory; theta 0.80; holdout never read).

Reads only existing training outputs (gitignored, under out/):
  out/strategy_a/summary.csv          run_strategy_a.py (taker; theta 0.80, sample "primary")
  out/strategy_a_maker/summary.csv    run_strategy_a_maker.py (v3 Amendment 5)
  out/strategy_a_maker/roc_ci.csv
Writes docs/results/maker_vs_taker.csv and docs/results/maker_vs_taker.md. Recomputes nothing; no variants row
(no new parameter combination). Attempts are defined the same way for both: the favorite (or underdog) cleared
theta and an order was sent. Taker attempts = entered + "no post-decision trade" skips (no trade within 5 min
after t + latency); maker attempts = orders placed (the 6 underdog orders whose limit, as-of - 1 c, would be
below the 1 c grid are skips, not attempts). The maker direct line uses the TAKER fee formula: an upper bound,
Kalshi's maker fee is not confirmed first-party.

Usage: python scripts/maker_vs_taker.py
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

A_SUM = Path("out/strategy_a/summary.csv")
M_SUM = Path("out/strategy_a_maker/summary.csv")
M_CI = Path("out/strategy_a_maker/roc_ci.csv")
OUT_CSV = Path("docs/results/maker_vs_taker.csv")
OUT_MD = Path("docs/results/maker_vs_taker.md")
THETA = 0.80
QTY = 10


def taker() -> list[dict]:
    s = pd.read_csv(A_SUM)
    s = s[(s["theta"].round(2) == THETA) & (s["sample"] == "primary")]
    out = []
    s = s.rename(columns={"skip_no post-decision trade": "no_post_trade"})
    for r in s.itertuples():
        attempts = int(r.entered) + int(r.no_post_trade)
        out.append({"strategy": "A taker", "leg": r.leg, "attempts": attempts, "fills": int(r.entered),
                    "fill_rate": r.entered / attempts, "mean_fill": r.mean_fill, "win_rate": r.win_rate,
                    "win_minus_fill": r.win_minus_fill,
                    "roc_webull": r.roc_webull, "roc_webull_ci_lo": r.roc_webull_ci_lo,
                    "roc_webull_ci_hi": r.roc_webull_ci_hi,
                    "roc_direct": r.roc_direct, "roc_direct_ci_lo": r.roc_direct_ci_lo,
                    "roc_direct_ci_hi": r.roc_direct_ci_hi,
                    "pnl_webull": r.pnl_webull_total, "pnl_direct": r.pnl_direct_total,
                    "net_cents_per_contract_webull": 100 * r.pnl_webull_total / (QTY * r.entered)})
    return out


def maker() -> list[dict]:
    s, ci = pd.read_csv(M_SUM), pd.read_csv(M_CI)
    ci = ci[ci["sample"] == "primary"]
    out = []
    for r in s.itertuples():
        w = ci[(ci["leg"] == r.leg) & (ci["line"] == "webull")].iloc[0]
        d = ci[(ci["leg"] == r.leg) & (ci["line"].str.startswith("direct"))].iloc[0]
        out.append({"strategy": "A-maker", "leg": r.leg, "attempts": int(r.attempts), "fills": int(r.fills),
                    "fill_rate": r.fill_rate, "mean_fill": r.mean_fill, "win_rate": r.win_rate,
                    "win_minus_fill": r.win_minus_fill,
                    "roc_webull": r.roc_webull, "roc_webull_ci_lo": w.ci_lo, "roc_webull_ci_hi": w.ci_hi,
                    "roc_direct": r.roc_direct_taker_upper, "roc_direct_ci_lo": d.ci_lo, "roc_direct_ci_hi": d.ci_hi,
                    "pnl_webull": r.pnl_webull, "pnl_direct": r.pnl_direct_taker_upper,
                    "net_cents_per_contract_webull": 100 * r.pnl_webull / (QTY * r.fills)})
    return out


def main() -> None:
    t = pd.DataFrame(taker() + maker())
    t["leg"] = t["leg"].replace({"placebo (underdog)": "underdog placebo"})
    t = t.sort_values(["leg", "strategy"], ascending=[True, False]).reset_index(drop=True)
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    t.to_csv(OUT_CSV, index=False)

    def ci(r, line):
        return f"{r[f'roc_{line}']:+.4f} [{r[f'roc_{line}_ci_lo']:+.4f}, {r[f'roc_{line}_ci_hi']:+.4f}]"

    lines = ["# Strategy A: taker vs maker (training, theta 0.80, exploratory)", "",
             "Generated by scripts/maker_vs_taker.py from out/strategy_a/summary.csv and out/strategy_a_maker/ "
             "(training games only, kickoff before 2026-08-01). 10 contracts per trade. ROC = return on capital per "
             "trade, game-level bootstrap 95% CI (2,000 resamples, seed 20261003). Maker 'direct' uses the taker fee "
             "formula (upper bound; Kalshi's maker fee is not confirmed first-party).", "",
             "| Strategy | Leg | Attempts | Fills | Fill rate | Mean fill | Win rate | Win - fill | ROC Webull [95% CI] "
             "| ROC direct [95% CI] | Net c/contract (Webull) |",
             "|---|---|---|---|---|---|---|---|---|---|---|"]
    for _, r in t.iterrows():
        lines.append(f"| {r.strategy} | {r.leg} | {r.attempts} | {r.fills} | {r.fill_rate:.3f} | {r.mean_fill:.4f} | "
                     f"{r.win_rate:.3f} | {r.win_minus_fill:+.4f} | {ci(r, 'webull')} | {ci(r, 'direct')} | "
                     f"{r.net_cents_per_contract_webull:+.2f} |")
    fav = t[t["leg"] == "favorite"].set_index("strategy")
    lines += ["", "Notes:",
              f"- Same decisions: both legs send an order on the same {fav.loc['A taker', 'attempts']} favorite "
              "decisions. The taker fills most of them (any trade within 5 min after t + 1 s); the maker fills "
              f"only {fav.loc['A-maker', 'fills']}, where a later trade went through its limit (as-of - 1 c).",
              "- Underdog placebo: 6 maker orders are skipped because the limit would be below the 1 c grid (as-of "
              "price 0.01), so maker attempts are 351 vs 357. All 23 maker underdog fills lost (ROC -1, so the CI "
              "is degenerate).",
              f"- The maker favorite sample is {fav.loc['A-maker', 'fills']} trades; its CI includes 0 and is "
              f"{(fav.loc['A-maker', 'roc_webull_ci_hi'] - fav.loc['A-maker', 'roc_webull_ci_lo']) / (fav.loc['A taker', 'roc_webull_ci_hi'] - fav.loc['A taker', 'roc_webull_ci_lo']):.1f}x as wide as the taker's. The maker's lower mean fill is consistent with adverse selection: it "
              "fills only when the price trades down through its limit, so its fills are not a random subset of the "
              "taker's.",
              "- Exploratory: A-maker was pre-registered in v3 Amendment 5; this table compares, it selects nothing."]
    OUT_MD.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
