"""Numbers sheet for the note: one row per value in results/numbers.json, so no number is ever typed by hand.

Writes docs/note/numbers_sheet.md with columns: placeholder, value, unit, source script, Alden (blank, initials).
Placeholder names are {{STRATEGY_SAMPLE_METRIC}}: the sample is TRAIN for training keys and OOS for keys starting
"OOS."; e.g. "A.sharpe" -> {{A_TRAIN_SHARPE}}, "OOS.A.sharpe" -> {{A_OOS_SHARPE}},
"B.french.t_alpha_daily" -> {{B_TRAIN_FRENCH_T_ALPHA_DAILY}}, "training.season_first_day" -> {{TRAIN_SEASON_FIRST_DAY}}.
Re-run after the holdout run (OOS keys) to refresh every value.

Usage: python scripts/numbers_sheet.py [results/numbers.json] [docs/note/numbers_sheet.md]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UNITS = [  # (regex on the metric part of the key, unit), first match wins
    (r"cents", "cents per contract"), (r"(^|_)pnl|pnl_|drawdown_dollars|worst_month_pnl|notional", "dollars"),
    (r"capital_base", "dollars"), (r"ann_return|ann_vol", "fraction of capital base, annualized"),
    (r"drawdown_of_base", "fraction of capital base"),
    (r"deflated", "probability"),
    (r"sharpe_daily", "daily Sharpe (not annualized)"), (r"sharpe", "Sharpe, annualized x sqrt(365)"), (r"^t_|\.t_|french\.t_", "t-statistic (Newey-West 5 lags)"),
    (r"r_squared", "R squared"), (r"beta|alpha", "regression coefficient (daily return units)"),
    (r"pearson|corr", "correlation"), (r"skew", "skewness"), (r"contracts_per_day", "contracts per day"),
    (r"days|n_trades|n_factor_days|^n$|attempts|fills|n_games|n_qualifying|n_candidates|n_excluded", "count"),
    (r"day$|date|month", "date"), (r"theta", "price threshold"), (r"roc", "return on capital"),
]


def placeholder(key: str) -> str:
    parts = key.split(".")
    if parts[0] == "OOS":
        sample, parts = "OOS", parts[1:]
    elif parts[0] == "training":
        return "{{TRAIN_" + "_".join(p.upper() for p in parts[1:]) + "}}"
    else:
        sample = "TRAIN"
    strat, rest = parts[0], parts[1:]
    name = "_".join([strat, sample] + rest)
    return "{{" + re.sub(r"[^A-Za-z0-9]+", "_", name).upper().strip("_") + "}}"


def unit(key: str, value) -> str:
    if isinstance(value, str) and not re.match(r"^\d{4}-\d{2}", value):
        return "text"
    if isinstance(value, (dict, list)):
        return "structured"
    metric = key.split(".", 1)[-1]
    for rx, u in UNITS:
        if re.search(rx, metric):
            return u
    return ""


def fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:.6g}"
    if isinstance(v, (dict, list)):
        return json.dumps(v)
    return str(v).replace("|", "/")


def main() -> None:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "results" / "numbers.json"
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "docs" / "note" / "numbers_sheet.md"
    num = json.loads(src.read_text())
    lines = ["# Numbers sheet", "",
             f"Generated by scripts/numbers_sheet.py from {src.relative_to(ROOT) if src.is_relative_to(ROOT) else src} "
             f"({len(num)} values). Every number in the note comes from this table; Alden initials each row after his "
             "hand check. Do not edit by hand: re-run the script.", "",
             "| placeholder | value | unit | source | Alden |", "|---|---|---|---|---|"]
    for k in sorted(num):
        v = num[k]["value"]
        lines.append(f"| `{placeholder(k)}` | {fmt(v)} | {unit(k, v)} | {num[k].get('source', '')} |  |")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}: {len(num)} rows")


if __name__ == "__main__":
    main()
